### ISSUE TITLE
error message on install in chrome.

### ISSUE THREAD

**Issue by dlefcoe** [rubenvar/csv-reader#11]
version:
Chrome is up to date
Version 96.0.4664.45 (Official Build) (64-bit)

error message reads like:
this doesn't work, report error.

please advise.

**Comment by dlefcoe** [comment]
Here is the full error message:
---------------------------------


This doesn't seem to work here, please try a different page...


Feeling daring?

Try anyway! (but no promises)
Is this an error? Please report it.

**Comment by rubenvar** [comment]
Hey @dlefcoe, just tested the extension with that exact version of Chrome in [the test page](https://rubenvara.s3-eu-west-1.amazonaws.com/csv/dataNov-2-2020.csv) linked in the readme and it works fine.

That error screen usually shows because the extension doesn't recognize the page as a `.csv` page. If it's a false positive and the page is readable by the extension, you can click _Try Anyway_ to try.

If you let me know which page you got the error at, I can take a look at it.
